name: CI/CD Pipeline

on:
  push:
    branches: [develop]   
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 main.py test_main.py

  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s . -p "test_main.py"

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Docker image
        run: docker build -t pi3:latest .

  deploy:
    name: Push to main branch
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Merge develop into main safely and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main || git checkout -b main
          git checkout main
          git merge develop --no-ff -X ours -m "Auto-merge develop into main after successful CI/CD"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Ilya932/TVPO3.git main
