name: Test and Deploy Main.py on Push

on: [push]

jobs:
  test_main_py:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unittests
        run: |
          python -m unittest tests

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'  # Деплой будет выполняться только для ветки main и при успешных тестах

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for deploy
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync  # Устанавливаем rsync для синхронизации файлов на сервер

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          sudo mkdir -p /var/www/project  # Создаем директорию для деплоя
          rsync -av --no-perms --no-owner --no-group --exclude '.git*' ./ /var/www/project/  # Копируем файлы на сервер
          echo "Successfully deployed"
