name: Test and Deploy Main.py on Push

on: [push]

jobs:
  test_main_py:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unittests
        run: |
          python -m unittest tests

  
