name: CI/CD Pipeline

on:
  push:
    branches: [develop]   
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 main.py tests/test.py

  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s . -p "tests/test.py"

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Docker image
        run: docker build -t pi3:latest .

  deploy:
    name: Sync main with develop
    runs-on: ubuntu-latest
    needs: docker-build  # или test, если docker не обязателен для деплоя
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync main to develop
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Получаем последний коммит из develop
          git checkout develop
          DEVELOP_COMMIT=$(git rev-parse HEAD)
          
          # Переключаемся на main и перезаписываем его
          git checkout main
          git reset --hard $DEVELOP_COMMIT
          
          # Пушим с force (без --force, но через push --force-with-lease для безопасности)
          git push origin main --force-with-lease

