name: CI/CD Pipeline

on:
  push:
    branches: [develop]   

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 main.py tests/test.py

  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s . -p "tests/test.py"

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Docker image
        run: docker build -t pi3:latest .

  deploy:
    name: Merge develop into main
    runs-on: ubuntu-latest
    steps:
      - name: Create PR into main
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          base: main
          title: "Auto-merge develop → main"
          body: "CI passed on develop, merging changes into main"
          commit-message: "Auto merge from develop"
          delete-branch: false

